### ISSUE TITLE
[紀錄] CSS 問題

### ISSUE THREAD

**Issue by benson00077** [benson00077/tlog-cms#1]
# Init
尤其 box-sizing 在這專案差很多，要覆蓋掉  `box-sizing` 預設的  `content-box` 
把 margin, padding 都初始化設置為 0 ，是因為不同瀏覽器的標籤所預設的值會不一樣。
```scss
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Roboto";   #MUI 建議
}
```
# Anchor Tag
調用 react-router-dom 的 `<NavLink>` ，子零件會是連結的名字(home, posts...etx)。
因為本質上是 anchor tag ，有需要調整 `display: block` 才會出現的狀況。
在調整樣式的時候要注意:  inline and block elements are different.  [ref](https://stackoverflow.com/questions/42709787/using-display-block-with-anchor-tag)
